
/* ═══ YM FINAL LAUNCH JS OVERRIDES ═══ */
(function(){
  const defaultStories=[
    {name:'A. Mohamed',country:'United Kingdom',visa:'Visitor Visa',flag:'🇬🇧',text:'A complete embassy file was prepared with a clear travel plan and supporting documents. Approved after professional review.',approved:true},
    {name:'S. Hassan',country:'Schengen',visa:'Tourist Visa',flag:'🇪🇺',text:'YM organized the hotel, flight plan, insurance and cover letter. The client received the visa within the expected timeline.',approved:true},
    {name:'M. Ali',country:'UAE',visa:'Tourist Visa',flag:'🇦🇪',text:'Fast preparation and WhatsApp follow-up from booking until receiving the visa result.',approved:true}
  ];
  const defaultBlogs=[
    {title:'أسباب رفض فيزا أمريكا وكيف تتجنبها',tag:'USA Visa',text:'تعرف على أهم أسباب الرفض مثل ضعف الروابط، كشف بنكي غير واضح، أو إجابات غير منظمة في المقابلة.',approved:true},
    {title:'قائمة مستندات فيزا شنجن للمصريين',tag:'Schengen',text:'دليل سريع لأهم المستندات المطلوبة: كشف بنكي، تأمين سفر، حجز فندق، حجز طيران وخطاب عمل.',approved:true},
    {title:'كيف تجهز Cover Letter احترافي للسفارة؟',tag:'Cover Letter',text:'خطاب التغطية الجيد يشرح سبب السفر، خطة العودة، المدة، والقدرة المالية بشكل واضح ومقنع.',approved:true}
  ];
  window.getStories=function(){try{const x=JSON.parse(localStorage.getItem('ymSuccessStories')||'null');return Array.isArray(x)?x:defaultStories}catch{return defaultStories}};
  window.saveStories=function(v){localStorage.setItem('ymSuccessStories',JSON.stringify(v.slice(0,60))); renderStories(); renderAdminStories();};
  window.renderStories=function(){const el=document.getElementById('successStoriesGrid'); if(!el)return; const rows=getStories().filter(x=>x.approved!==false); el.innerHTML=rows.slice(0,9).map((x,i)=>`<article class="ym-premium-card"><span class="ym-story-badge">Approved</span><div class="flag">${safeText(x.flag||'🌍')}</div><h3>${safeText(x.visa||'Visa Success')}</h3><p>${safeText(x.text||'')}</p><div class="ym-mini-meta"><span>${safeText(x.name||'YM Client')}</span><span>${safeText(x.country||'Worldwide')}</span></div></article>`).join('')};
  window.adminAddStory=function(){const name=document.getElementById('adminStoryName').value.trim(),country=document.getElementById('adminStoryCountry').value.trim(),visa=document.getElementById('adminStoryVisa').value.trim(),flag=document.getElementById('adminStoryFlag').value.trim(),text=document.getElementById('adminStoryText').value.trim(); if(!visa||!text){toast('Add visa type and story text');return} const arr=getStories(); arr.unshift({name,country,visa,flag,text,approved:true,created:new Date().toISOString()}); saveStories(arr); ['adminStoryName','adminStoryCountry','adminStoryVisa','adminStoryFlag','adminStoryText'].forEach(id=>document.getElementById(id).value='')};
  window.deleteStory=function(i){const arr=getStories(); arr.splice(i,1); saveStories(arr)};
  window.toggleStory=function(i){const arr=getStories(); arr[i].approved=arr[i].approved===false; saveStories(arr)};
  window.renderAdminStories=function(){const el=document.getElementById('adminStoriesList'); if(!el)return; const arr=getStories(); el.innerHTML=arr.map((x,i)=>`<div class="review-admin-row"><div><strong>${safeText(x.flag||'🌍')} ${safeText(x.visa||'Story')}</strong> <small>${safeText(x.country||'')} · ${x.approved===false?'Hidden':'Shown'}</small><br><small>${safeText(x.text||'').slice(0,110)}</small></div><div style="display:flex;gap:6px"><button class="copy-btn" onclick="toggleStory(${i})">${x.approved===false?'Show':'Hide'}</button><button class="copy-btn danger-btn" onclick="deleteStory(${i})">Delete</button></div></div>`).join('')};

  window.getBlogs=function(){try{const x=JSON.parse(localStorage.getItem('ymBlogs')||'null');return Array.isArray(x)?x:defaultBlogs}catch{return defaultBlogs}};
  window.saveBlogs=function(v){localStorage.setItem('ymBlogs',JSON.stringify(v.slice(0,80))); renderBlogs(); renderAdminBlogs();};
  window.renderBlogs=function(){const el=document.getElementById('blogGrid'); if(!el)return; const rows=getBlogs().filter(x=>x.approved!==false); el.innerHTML=rows.slice(0,9).map((x,i)=>`<article class="ym-premium-card ym-blog-card"><div class="ym-blog-cover"></div><div class="ym-blog-body"><div class="ym-mini-meta"><span>${safeText(x.tag||'Visa Guide')}</span></div><h3>${safeText(x.title||'YM Visa Guide')}</h3><p>${safeText(x.text||'')}</p><a class="btn btn-gold" href="#booking" style="margin-top:14px" data-en="Book Consultation" data-ar="احجز استشارة">Book Consultation</a></div></article>`).join('')};
  window.adminAddBlog=function(){const title=document.getElementById('adminBlogTitle').value.trim(),tag=document.getElementById('adminBlogTag').value.trim(),text=document.getElementById('adminBlogText').value.trim(); if(!title||!text){toast('Add title and summary');return} const arr=getBlogs(); arr.unshift({title,tag,text,approved:true,created:new Date().toISOString()}); saveBlogs(arr); ['adminBlogTitle','adminBlogTag','adminBlogText'].forEach(id=>document.getElementById(id).value='')};
  window.deleteBlog=function(i){const arr=getBlogs(); arr.splice(i,1); saveBlogs(arr)};
  window.toggleBlog=function(i){const arr=getBlogs(); arr[i].approved=arr[i].approved===false; saveBlogs(arr)};
  window.renderAdminBlogs=function(){const el=document.getElementById('adminBlogsList'); if(!el)return; const arr=getBlogs(); el.innerHTML=arr.map((x,i)=>`<div class="review-admin-row"><div><strong>${safeText(x.title||'Article')}</strong> <small>${safeText(x.tag||'')} · ${x.approved===false?'Hidden':'Shown'}</small><br><small>${safeText(x.text||'').slice(0,110)}</small></div><div style="display:flex;gap:6px"><button class="copy-btn" onclick="toggleBlog(${i})">${x.approved===false?'Show':'Hide'}</button><button class="copy-btn danger-btn" onclick="deleteBlog(${i})">Delete</button></div></div>`).join('')};

  window.runEligibilityCheck=function(){const job=document.getElementById('eligJob').value,travel=document.getElementById('eligTravel').value,bank=document.getElementById('eligBank').value,country=document.getElementById('eligCountry').value; let score=45; if(job==='employed'||job==='business')score+=18; if(job==='student')score+=8; if(travel==='yes')score+=15; if(bank==='strong')score+=20; if(bank==='medium')score+=10; score=Math.max(20,Math.min(96,score)); const label=score>=75?(lang==='ar'?'جاهزية قوية':'Strong readiness'):score>=55?(lang==='ar'?'جاهزية متوسطة':'Medium readiness'):(lang==='ar'?'تحتاج مراجعة قوية':'Needs strong review'); const advice=score>=75?(lang==='ar'?'ملفك يبدو جيدًا مبدئيًا، احجز استشارة لتجهيز المستندات وخطاب التغطية.':'Your file looks promising. Book a consultation to prepare documents and cover letter.'):score>=55?(lang==='ar'?'هناك نقاط تحتاج تنظيم قبل التقديم. YM يمكنها مراجعة المستندات وتقوية الملف.':'Some points need organization before applying. YM can review and strengthen the file.'):(lang==='ar'?'يفضل عدم التقديم قبل مراجعة الملف كاملًا لتقليل مخاطر الرفض.':'Avoid applying before full file review to reduce rejection risk.'); document.getElementById('eligResult').innerHTML=`<div class="ym-result-score">${score}%</div><h3>${label} · ${safeText(country)}</h3><p>${advice}</p><a class="btn btn-gold" href="#booking" style="margin-top:14px">${lang==='ar'?'احجز استشارة الآن':'Book Consultation Now'}</a>`; trackYM('eligibility_check',{score,country});};

  const oldSubmit=window.submitClientReview;
  window.submitClientReview=function(){const name=document.getElementById('reviewName')?.value.trim(); const city=document.getElementById('reviewCity')?.value.trim(); const text=document.getElementById('reviewText')?.value.trim(); const stars=+document.getElementById('reviewStars')?.value||5; const initial=document.getElementById('reviewInitial')?.value.trim() || (name?name[0]:'Y'); if(!name||!text){toast(lang==='ar'?'اكتب الاسم والتقييم أولاً':'Please add your name and review');return} const arr=getReviews(); arr.unshift({name,city,initial,stars,text,approved:false,created:new Date().toISOString(),source:'client'}); saveReviews(arr); ['reviewName','reviewCity','reviewText','reviewInitial'].forEach(id=>{const el=document.getElementById(id); if(el) el.value=''}); toast(lang==='ar'?'تم استلام تقييمك وسيظهر بعد موافقة الإدارة':'Review received. It will appear after admin approval')};
  window.renderAdminReviews=function(){const el=document.getElementById('adminReviewsList'); if(!el)return; const arr=getReviews(); el.innerHTML=arr.map((r,i)=>`<div class="review-admin-row"><div><strong>${safeText(r.name)}</strong> ${r.approved===false?'<span class="pending-pill">Pending / Hidden</span>':''} <small>${reviewStars(Number(r.stars)||5)} · ${safeText(r.city||'')}</small><br><small>${safeText(r.text).slice(0,110)}</small></div><div style="display:flex;gap:6px"><button class="copy-btn" onclick="toggleReview(${i})">${r.approved===false?'Approve/Show':'Hide'}</button><button class="copy-btn danger-btn" onclick="deleteReview(${i})">Delete</button></div></div>`).join('')};
  const oldRenderAdmin=window.renderAdmin;
  window.renderAdmin=function(){ if(typeof oldRenderAdmin==='function') oldRenderAdmin(); renderAdminStories(); renderAdminBlogs(); };
  document.addEventListener('DOMContentLoaded',function(){renderStories();renderBlogs();});
  setTimeout(function(){renderStories();renderBlogs();renderAdminStories();renderAdminBlogs();},500);
})();
